using F0.CodeAnalysis;
using F0.Tests.Testing;
using Microsoft.CodeAnalysis.CSharp;

namespace F0.Tests.CodeAnalysis;

public class IsExternalInitGeneratorTests
{
	[Theory]
	[MemberData(nameof(InitOnlySetter_TheoryData))]
	public void SingleInitOnlySetter_Compile_GenerateType(string code, LanguageVersion langVersion) =>
#if HAS_SYSTEM_RUNTIME_COMPILERSERVICES_ISEXTERNALINIT
		RoslynUtilities.TestGenerator<IsExternalInitGenerator>(code, langVersion);
#else
		RoslynUtilities.TestGenerator<IsExternalInitGenerator>(code, GetGenerated(langVersion), langVersion);
#endif


	[Fact]
	public void MultipleInitOnlySetter_Compile_GenerateType()
	{
		const string code = @"
public class Class { public string InitOnlySetter { get; init; } }
public struct Struct { public string InitOnlySetter { get; init; } }
public readonly struct ReadOnlyStruct { public string InitOnlySetter { get; init; } }
public record Record(string InitOnlySetter);
public record class ReferenceType(string InitOnlySetter);
public readonly record struct ValueType(string InitOnlySetter);
";

#if HAS_SYSTEM_RUNTIME_COMPILERSERVICES_ISEXTERNALINIT
		RoslynUtilities.TestGenerator<IsExternalInitGenerator>(code);
#else
		RoslynUtilities.TestGenerator<IsExternalInitGenerator>(code, GetGenerated());
#endif
	}

	[Fact]
	public void NoInitOnlySetter_Compile_DoNotGenerateType()
	{
		const string code = @"
public class SetAccessor { public string InitOnlySetter { get; set; } }
public class NoSetAccessor { public string InitOnlySetter { get; } }
public record Record();
public record class ReferenceType();
public record struct ValueType(string InitOnlySetter);
";

		RoslynUtilities.TestGenerator<IsExternalInitGenerator>(code);
	}

	private static TheoryData<string, LanguageVersion> InitOnlySetter_TheoryData()
	{
		TheoryData<string, LanguageVersion> data = new();
		data.Add("public class Class { public string InitOnlySetter { get; init; } }", LanguageVersion.CSharp9);
		data.Add("public struct Struct { public string InitOnlySetter { get; init; } }", LanguageVersion.CSharp9);
		data.Add("public readonly struct ReadOnlyStruct { public string InitOnlySetter { get; init; } }", LanguageVersion.CSharp9);

		data.Add("public record Record(string InitOnlySetter);", LanguageVersion.CSharp9);
		data.Add("public record class ReferenceType(string InitOnlySetter);", LanguageVersion.CSharp10);
		data.Add("public readonly record struct ValueType(string InitOnlySetter);", LanguageVersion.CSharp10);
		return data;
	}

	private static string GetGenerated(LanguageVersion langVersion = LanguageVersion.Latest)
	{
		string generated = langVersion switch
		{
			<= LanguageVersion.CSharp8 => throw new NotSupportedException(),
			LanguageVersion.CSharp9 => @"// <auto-generated/>
#nullable enable

namespace System.Runtime.CompilerServices
{
	internal static class IsExternalInit
	{
	}
}
",
			>= LanguageVersion.CSharp10 => @"// <auto-generated/>
#nullable enable

namespace System.Runtime.CompilerServices;

internal static class IsExternalInit
{
}
",
			_ => throw new NotSupportedException(),
		};

		return generated;
	}
}
